# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.project_list')),
            ],
        ),
    ]
