# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-23 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0002_guest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='mode',
        ),
    ]
