# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-23 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0003_auto_20181023_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('describe', models.TextField(verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('project_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.project_list')),
            ],
        ),
        migrations.RemoveField(
            model_name='mode',
            name='name',
        ),
        migrations.DeleteModel(
            name='mode',
        ),
    ]
