# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0005_auto_20181023_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='describe',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
